### ISSUE TITLE
Hello, i have a question about pre-processing step.

### ISSUE THREAD

**Issue by raspatiocan** [pss1207/sleep_apnea#6]
Hi, i'm student from indonesia, I like what you make, I need almost 2 months to understand the program that you made, and I have a question about the program you made. I want to ask about the variables / parameters used in this program, such as `MARGIN = 10
FS_INTP = 4
MAX_HR = 300.0
MIN_HR = 20.0
MIN_RRI = 1.0 / (MAX_HR / 60.0) * 1000
MAX_RRI = 1.0 / (MIN_HR / 60.0) * 1000`
my question is where to get these values? Are these values obtained freely (as needed) or are there theories / references for these values? 
Thank you for your attention:)

**Comment by pss1207** [comment]
Hi Muhammad,

Thanks for asking.

I applied resampling to RR intervals because the RR intervals are not uniform. The above figure shows the time of each RR interval. 
The FS_INTP = 4Hz is usually used for preprocessing of the frequency domain HRV. You can find a lot of papers which have researched frequency domain HRV.
The MARGIN is for interpolating the first sample and the last sample. It’s defined by me and you can change the value or apply better method.
MIN_HR and MAX_HR are minimum and maximum heart rate. Physiologically the range is between 20 and 300 BPM. MIN_RRI and MAX_RRI are calculated based on the MIN_HR and MAX_HR.

Thanks,
Sangshik

**Comment by raspatiocan** [comment]
thanks for the answer, this really helps a lot in understanding the pre-processing stages. There is one more question, did age and gender affect the results?
and I'm sorry if I'm interrupting you who might be busy now.

Best Regards,
Fauzan

**Comment by pss1207** [comment]
Hi Fauzan,

Age and gender are affect the prediction.
I used LSTM for RR Interval and QRS amplitude and MLP for gender and age.
Those networks were combined.
RR intervals and QRS amplitudes relates to the autonomic nervous system and old people and man have higher probability of sleep apnea.

Thanks,
Sangshik

**Comment by raspatiocan** [comment]
Thanks again for answering, hopefully the answers given can be useful for everyone who reads this. because for now I have got the answers I need, then I will close this issues. I hope in the future you can help again if I have trouble.
